# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Funcionario', '0001_initial'),
        ('Estoque_Loja', '0001_initial'),
        ('Endereco', '0001_initial'),
        ('Inventario', '0001_initial'),
        ('Proprietario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidade', models.IntegerField()),
                ('area', models.FloatField()),
                ('franquia', models.BooleanField()),
                ('cnpj', models.IntegerField()),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Endereco.Endereco')),
                ('estoque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Estoque_Loja.Estoque_Loja')),
                ('gerente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Funcionario.Funcionario')),
                ('inventario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventario.Inventario')),
                ('proprietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Proprietario.Proprietario')),
            ],
        ),
    ]
