# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='endereco',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Endereco.Endereco'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loja',
            name='estoque',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Estoque_Loja.Estoque_Loja'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loja',
            name='gerente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Funcionario.Funcionario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loja',
            name='inventario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Inventario.Inventario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loja',
            name='proprietario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Proprietario.Proprietario'),
            preserve_default=False,
        ),
    ]
