# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alimento', '0002_alimento_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque_Loja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantida', models.IntegerField()),
                ('alimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Alimento.Alimento')),
            ],
        ),
    ]
