# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tipo_de_Ingrediente', '0001_initial'),
        ('Alimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tipo_de_Ingrediente.Tipo_de_Ingrediente'),
        ),
    ]
