# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alimento', '0002_alimento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='tipo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Tipo_de_Ingrediente.Tipo_de_Ingrediente'),
            preserve_default=False,
        ),
    ]
