# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alimento', '0003_auto_20161124_0300'),
        ('Distribuidor_Tercerizado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidores_Tercerizados_Bebidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimento', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Alimento.Alimento')),
                ('distribuidor_tercerizado', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Distribuidor_Tercerizado.Distribuidor_Tercerizado')),
            ],
        ),
    ]
