# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Veiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='centro_distribuicao',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Centro_Distribuicao.Centro_Distribuicao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='disponibilidade',
            field=models.BooleanField(default=False),
        ),
    ]
