# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario_Loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='funcionario_loja',
            table='funcionario_loja',
        ),
    ]
