# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Funcionario', '0001_initial'),
        ('Pesquisa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota_fiscal', models.IntegerField()),
                ('data', models.DateField()),
                ('total', models.FloatField()),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Funcionario.Funcionario')),
                ('pesquisa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pesquisa.Pesquisa')),
            ],
        ),
    ]
